Repository vedanshjainvj/Job-Hive, pull requests merged in 2025-01, with the labels that each got.

#19 [ENHANCEMENT] : Issue In Responsiveness of Homepage
  client/package-lock.json
  client/package.json
  client/src/components/CategoryCarousel.jsx
  client/src/components/HeroSection.jsx
  client/src/components/Home.jsx
  client/src/components/LatestJobs.jsx
  client/src/components/shared/Footer.jsx
  client/src/components/shared/Navbar.jsx
Labels: SWOC, ✅ SWOC Accepted PR

#20 [FEATURE] : Google OAuth functionality and zod validation
  client/package-lock.json
  client/package.json
  client/src/components/admin/CompanyCreate.jsx
  client/src/components/admin/CompanySetup.jsx
  client/src/components/admin/PostJob.jsx
  client/src/components/auth/Login.jsx
  client/src/components/auth/OAuth.jsx
  client/src/components/auth/Signup.jsx
  client/src/components/ui/sonner.jsx
  client/src/components/utils/firebase.js
  client/src/components/utils/formValidation.js
  server/controllers/job.controller.js
  server/controllers/user.controller.js
  server/models/user.model.js
  server/routes/user.routes.js
Labels: SWOC, ✅ SWOC Accepted PR, 💰 bounty

#33 [BUG] : Company setup page
  client/src/components/admin/CompanySetup.jsx
  client/src/components/utils/formValidation.js
Labels: SWOC, ⭐ level 1, ✅ SWOC Accepted PR

#35 [BUG FIX] : "Number of Positions" Field Stores Value as String
  client/src/components/admin/PostJob.jsx
Labels: SWOC, ⭐ level 1, ✅ SWOC Accepted PR

#58 [FEATURE] : Added Generation & Sending of Offer Letter
  client/src/components/admin/ApplicantsTable.jsx
  server/controllers/application.controller.js
  server/html/offer-letter.js
  server/package-lock.json
  server/package.json
  server/routes/application.route.js
  server/utils/pdf-generator.js
  server/utils/sendMail.js
Labels: SWOC, ⭐🥇🏆 advance, ✅ SWOC Accepted PR, 💰 bounty
